version: '3.8'

services:
  dev-database:
    image: postgres:15.0
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=testdb
    networks:
      - nestjs-network

networks:
  nestjs-network:
